import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent

# Database: PostgreSQL (when POSTGRES_HOST set) or SQLite (fallback)
POSTGRES_HOST = os.getenv("POSTGRES_HOST", "")
POSTGRES_PORT = int(os.getenv("POSTGRES_PORT", "5432"))
POSTGRES_USER = os.getenv("POSTGRES_USER", "predictor")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD", "")
POSTGRES_DB = os.getenv("POSTGRES_DB", "predictions")
USE_POSTGRES = bool(POSTGRES_HOST and POSTGRES_PASSWORD)

# SQLite fallback (used when USE_POSTGRES is False)
DB_PATH = BASE_DIR / "data" / "predictions.db"

# Nifty 200: Nifty 50 + Nifty Next 50 + Nifty Midcap 100 (Yahoo Finance NSE .NS suffix)
# Deduplicated to 200 unique tickers.
_NIFTY_200_RAW = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS",
    "HINDUNILVR.NS", "SBIN.NS", "BHARTIARTL.NS", "KOTAKBANK.NS", "ITC.NS",
    "LT.NS", "AXISBANK.NS", "BAJFINANCE.NS", "ASIANPAINT.NS", "MARUTI.NS",
    "SUNPHARMA.NS", "TITAN.NS", "ULTRACEMCO.NS", "NESTLEIND.NS", "WIPRO.NS",
    "HCLTECH.NS", "POWERGRID.NS", "NTPC.NS", "TATAMOTORS.NS", "ADANIENT.NS",
    "ADANIPORTS.NS", "JSWSTEEL.NS", "TATASTEEL.NS", "BAJAJFINSV.NS", "TECHM.NS",
    "ONGC.NS", "COALINDIA.NS", "HDFCLIFE.NS", "SBILIFE.NS", "DIVISLAB.NS",
    "DRREDDY.NS", "GRASIM.NS", "CIPLA.NS", "APOLLOHOSP.NS", "EICHERMOT.NS",
    "HEROMOTOCO.NS", "BPCL.NS", "INDUSINDBK.NS", "TATACONSUM.NS", "BRITANNIA.NS",
    "M&M.NS", "BAJAJ-AUTO.NS", "DABUR.NS", "VEDL.NS", "HINDALCO.NS",
    "LTIM.NS", "PIDILITIND.NS", "SIEMENS.NS", "ADANIGREEN.NS", "PERSISTENT.NS",
    "BEL.NS", "HAL.NS", "TVSMOTOR.NS", "TRENT.NS", "ZYDUSLIFE.NS",
    "DMART.NS", "ICICIPRULI.NS", "BAJAJHLDNG.NS", "MARICO.NS", "COLPAL.NS",
    "MOTHERSON.NS", "SRF.NS", "AUROPHARMA.NS", "AMBUJACEM.NS", "HAVELLS.NS",
    "NAUKRI.NS", "TORNTPHARM.NS", "ABB.NS", "DALBHARAT.NS", "BOSCHLTD.NS",
    "LALPATHLAB.NS", "MRF.NS", "PIIND.NS", "BERGEPAINT.NS", "INDIGO.NS",
    "MCDOWELL-N.NS", "GAIL.NS", "CONCOR.NS", "APOLLOTYRE.NS", "BIOCON.NS",
    "GODREJCP.NS", "TATAPOWER.NS", "JINDALSTEL.NS", "VOLTAS.NS", "ABCAPITAL.NS",
    "GLENMARK.NS", "SAIL.NS", "UBL.NS", "ESCORTS.NS", "PNB.NS",
    "IDEA.NS", "CANBK.NS", "BANKBARODA.NS", "UNIONBANK.NS", "IOB.NS",
    "FEDERALBNK.NS", "BALKRISIND.NS", "JKCEMENT.NS", "RECLTD.NS", "OBEROIRLTY.NS",
    "ABBOTINDIA.NS", "AEGISLOG.NS", "AIAENG.NS", "ALKEM.NS", "ALKYLAMINE.NS",
    "APLAPOLLO.NS", "AUBANK.NS", "ASTRAL.NS", "ATUL.NS", "BALRAMCHIN.NS",
    "BANDHANBNK.NS", "BATAINDIA.NS", "BHARATFORG.NS", "BHEL.NS", "BIKAJI.NS",
    "BLUEDART.NS", "BLUESTARCO.NS", "BSE.NS", "CANFINHOME.NS", "CHALET.NS",
    "CHAMBLFERT.NS", "CROMPTON.NS", "CUMMINSIND.NS", "DIXON.NS", "DEEPAKNTR.NS",
    "DELTACORP.NS", "EIHOTEL.NS", "EXIDEIND.NS", "FSL.NS", "GNFC.NS",
    "GRANULES.NS", "GRAPHITE.NS", "GUJGAS.NS", "HUDCO.NS", "IDFC.NS",
    "IDFCFIRSTB.NS", "IGL.NS", "INDIACEM.NS", "INDIAMART.NS", "INDHOTEL.NS",
    "INDIGOPNTS.NS", "INDUSTOWER.NS", "IPCALAB.NS", "JSWENERGY.NS", "JTLINFRA.NS",
    "LAURUSLABS.NS", "LICHSGFIN.NS", "LTTS.NS", "MANAPPURAM.NS", "METROPOLIS.NS",
    "MPHASIS.NS", "NAM-INDIA.NS", "NATCOPHARMA.NS", "NMDC.NS", "OFSS.NS",
    "PAGEIND.NS", "PEL.NS", "PETRONET.NS", "PFC.NS", "POLYCAB.NS",
    "RAMCOCEM.NS", "RATNAMANI.NS", "RBLBANK.NS", "SCHAEFFLER.NS", "SHREECEM.NS",
    "STAR.NS", "SUPREMEIND.NS", "SYNGENE.NS", "TATACOMM.NS", "TATATECH.NS",
    "THERMAX.NS", "TIMKEN.NS", "TORNTPOWER.NS", "UPL.NS", "VGUARD.NS",
    "WHIRLPOOL.NS", "AARTIIND.NS", "ACC.NS", "AJANTPHARM.NS", "ASHOKLEY.NS",
    "ASHOKA.NS", "BAJAJELEC.NS", "COFORGE.NS", "CREDITACC.NS", "DEEPAKFERT.NS",
    "ESCORTS.NS", "FORTIS.NS", "GLENMARK.NS", "GMRINFRA.NS", "HINDZINC.NS",
    "ICICIGI.NS", "JKCEMENT.NS", "LUPIN.NS", "MFSL.NS", "NIACL.NS",
    "PAGEIND.NS", "PEL.NS", "PFIZER.NS", "SANOFI.NS", "TATACOMM.NS",
]
NIFTY_200_TICKERS = list(dict.fromkeys(_NIFTY_200_RAW))[:200]

PREDICTION_COUNT = 5

# Risk/Reward ratio for target calculation
RISK_REWARD_RATIO = 2.0

# ATR multiplier for stop-loss
ATR_MULTIPLIER = 1.5

# Lookback period for technical analysis (trading days)
LOOKBACK_DAYS = 60

# Retraining threshold — retrain if win rate drops below this
RETRAIN_ACCURACY_THRESHOLD = 0.40

EMAIL_SENDER = os.getenv("EMAIL_SENDER", "")
EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD", "")
EMAIL_RECIPIENT = os.getenv("EMAIL_RECIPIENT", "")
SMTP_SERVER = os.getenv("SMTP_SERVER", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))

SCHEDULE_HOUR = 16  # 4:00 PM IST
SCHEDULE_MINUTE = 0
TIMEZONE = "Asia/Kolkata"
